language: haxe

install:
  - haxelib install flixel
  - haxelib install flixel-ui
  - haxelib install lime
  - haxelib install openfl

script:
  - haxelib run openfl build "Project.xml" html5
  - haxelib run openfl build "Project.xml" linux